arcanys_sso_auth_metadata:
    path:     /metadata
    defaults: { _controller: ArcanysSSOAuthBundle:Sp:metadata }


arcanys_sso_auth_acs:
    path:     /metadata
    defaults: { _controller: ArcanysSSOAuthBundle:Sp:acs }

arcanys_sso_auth_sls:
    path:     /metadata
    defaults: { _controller: ArcanysSSOAuthBundle:Sp:sls }
