services:
#    arcanys_sso_auth.example:
#        class: Arcanys\SSOAuthBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    arcanys_sso_auth.sso_authenticator:
        class:  Arcanys\SSOAuthBundle\Security\SSOAuthenticator
        arguments: [ @arcanys_sso_auth.saml2, @session ]

    arcanys_sso_auth.saml2:
        class:  Arcanys\SSOAuthBundle\Service\Saml2
        arguments: [ %arcanys_sso_auth%, @router ]

    arcanys_sso_auth.saml2_metadata_facade:
        class:  Arcanys\SSOAuthBundle\Service\Saml2MetadataFacade
        arguments: [ %arcanys_sso_auth%, @router ]

    arcanys_sso_auth.user_provider:
        class: Arcanys\SSOAuthBundle\Security\User\SSOUserProvider
        arguments: [%arcanys_sso_auth%,  @doctrine ]
