services:
#    arcanys_sso_auth.example:
#        class: Arcanys\SSOAuthBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    arcanys_sso_auth.sso_authenticator:
        class:  Arcanys\SSOAuthBundle\Security\SSOAuthenticator
        arguments: [ @arcanys_sso_auth.saml2 ]

    arcanys_sso_auth.saml2:
        class:  Arcanys\SSOAuthBundle\Service\Saml2
        arguments: [ @service_container ]
